export type MockServerData = {
    title: string[];
    description: string[];
    date: string[];
    city: string[];
    preview: string[];
    photos: string[];
    isPremium: string[];
    isFavorite: string[];
    rating: string[];
    rooms: string[];
    guests: string[];
    price: string[];
    comforts: string[];
    name: string[];
    email: string[];
    avatar: string[];
    password: string[];
    role: string[];
    latitude: string[];
    longitude: string[];
};
